apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: generator
  name: generator
spec:
  template:
    metadata:
      labels:
        app: generator
    spec:
      serviceAccountName: generator
      containers:
      - image: generator:latest
        args:
        - --serviceaccount=gitops-reconciler
        - --namespace=dev-team
        - --server=https://capsule-proxy.default.svc:9001
        - --server-tls-secret-name=capsule-proxy
        imagePullPolicy: IfNotPresent
        name: generator
      restartPolicy: OnFailure
